name: Keep Render Backend Awake

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/14 * * * *'
  workflow_dispatch: # Optional manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Ping to Render Backend
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://blogapp-backend-gkmv.onrender.com
